### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by e111077**
Tests may fail due to lack of format or types not being updated. It would be much appreciated if the element owner can do that run and help parallelize the work on that front.

### CODE REVIEW

**Comment by e111077** [comment]
ping

**Comment by bicknellr** [comment]
This seems to be a legitimate failure in Safari 11.

**Comment by bicknellr** [comment]
... which is already a problem in master, not related to this PR, AFAICT.

**Comment by aomarks** [comment]
Tests are failing with a real error:
```
OS X 10.12 safari 11     ✖ test/small-devices.html » on small devices » drawer can be opened
  AssertionError: expected -256 to equal 0 (http://localhost:8081/components/chai/chai.js:263)
OS X 10.12 safari 11     ✖ test/small-devices.html » on small devices » right-drawer can be closed
  AssertionError: expected 1156 to equal 900 (http://localhost:8081/components/chai/chai.js:263)
```

**Comment by e111077** [comment]
spoken in private: test failures not in scope of this PR; only getting tests to run

**Pull request merged**
